const SUBSTATS = {
  FIGHT_PROP_BASE_ATTACK: "weaponAtk",
  FIGHT_PROP_HP: "hp",
  FIGHT_PROP_ATTACK: "atk",
  FIGHT_PROP_DEFENSE: "def",
  FIGHT_PROP_HP_PERCENT: "hp%",
  FIGHT_PROP_ATTACK_PERCENT: "atk%",
  FIGHT_PROP_DEFENSE_PERCENT: "def%",
  FIGHT_PROP_CRITICAL: "cr",
  FIGHT_PROP_CRITICAL_HURT: "cd",
  FIGHT_PROP_CHARGE_EFFICIENCY: "er",
  FIGHT_PROP_HEAL_ADD: "hb",
  FIGHT_PROP_ELEMENT_MASTERY: "em",
  FIGHT_PROP_PHYSICAL_ADD_HURT: "phy%",
  FIGHT_PROP_FIRE_ADD_HURT: "pyro%",
  FIGHT_PROP_ELEC_ADD_HURT: "electro%",
  FIGHT_PROP_WATER_ADD_HURT: "hydro%",
  FIGHT_PROP_WIND_ADD_HURT: "anemo%",
  FIGHT_PROP_ICE_ADD_HURT: "cryo%",
  FIGHT_PROP_ROCK_ADD_HURT: "geo%",
  FIGHT_PROP_GRASS_ADD_HURT: "dendro%"
}
export default SUBSTATS;  